app-name = "tomato-coffee"
app-version = "v0.1.0"
secret-key = "m4is3cr3tk3j"
region = "us"
github-client-id = "kli3ntiD"
github-client-secret = "kli3nts3cr3t"
github-redirect-uri = "https://node-postgre-starter.herokuapp.com/auth/github/callback"